apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: insights-ocp-api
    name: insights-ocp-api
  spec:
    replicas: 1
    selector:
      app: insights-ocp-api
      deploymentconfig: insights-ocp-api
    template:
      metadata:
        labels:
          app: insights-ocp-api
          deploymentconfig: insights-ocp-api
      spec:
        containers:
        - image: docker.io/rexwhite/insights-ocp-api:latest
          name: insights-ocp-api
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: DATABASE
                name: insights-ocp-db
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: PASSWORD
                name: insights-ocp-db
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ROOT_PASSWORD
                name: insights-ocp-db
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: USER
                name: insights-ocp-db
          - name: MYSQL_HOST
            value: insights-ocp-db
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - insights-ocp-api
        from:
          kind: ImageStreamTag
          name: insights-ocp-api:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: insights-ocp-api
    name: insights-ocp-api
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: insights-ocp-api
      deploymentconfig: insights-ocp-api
