apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: insights-ocp-api
    name: node
  spec:
    tags:
    - from:
        kind: DockerImage
        name: node:6
      name: "6"
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: insights-ocp-api
    name: insights-ocp-api
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: insights-ocp-api
    name: insights-ocp-api
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: insights-ocp-api:latest
    source:
      git:
        uri: https://github.com/RedHatInsights/insights-ocp-api
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: node:6
      type: Docker
    triggers:
    - github:
        secret: -tHBg0gMg93F96UqygBU
      type: GitHub
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: insights-ocp-api
    name: insights-ocp-api
  spec:
    replicas: 1
    selector:
      app: insights-ocp-api
      deploymentconfig: insights-ocp-api
    template:
      metadata:
        labels:
          app: insights-ocp-api
          deploymentconfig: insights-ocp-api
      spec:
        containers:
        - image: docker-registry.default.svc:5000/insights-scan/insights-ocp-api:latest
          name: insights-ocp-api
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: MYSQL_HOST
            value: insights-ocp-db
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - insights-ocp-api
        from:
          kind: ImageStreamTag
          name: insights-ocp-api:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: insights-ocp-api
    name: insights-ocp-api
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: insights-ocp-api
      deploymentconfig: insights-ocp-api
kind: List
metadata: {}
