apiVersion: v1
items:
# - apiVersion: v1
#   kind: ImageStream
#   metadata:
#     labels:
#       app: insights-ocp-scanner
#     name: centos
#   spec:
#     tags:
#     - from:
#         kind: DockerImage
#         name: centos:centos7
#       name: centos7
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: insights-ocp-scanner
    name: insights-ocp-scanner
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: insights-ocp-scanner
    name: insights-ocp-scanner
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: insights-ocp-scanner:latest
    source:
      git:
        uri: https://github.com/RedHatInsights/insights-ocp-scanner
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:centos7
      type: Docker
    triggers:
    - github:
        secret: fW-QXyfddMKM9zZ2PtAM
      type: GitHub
    - type: ConfigChange
# - apiVersion: v1
#   kind: DeploymentConfig
#   metadata:
#     labels:
#       app: insights-ocp-scanner
#     name: insights-ocp-scanner
#   spec:
#     selector:
#       app: insights-ocp-scanner
#       deploymentconfig: insights-ocp-scanner
#     template:
#       metadata:
#         labels:
#           app: insights-ocp-scanner
#           deploymentconfig: insights-ocp-scanner
#       spec:
#         containers:
#         - image: insights-ocp-scanner:latest
#           name: insights-ocp-scanner
#           resources: {}
#     triggers:
#     - type: ConfigChange
#     - imageChangeParams:
#         automatic: true
#         containerNames:
#         - insights-ocp-scanner
#         from:
#           kind: ImageStreamTag
#           name: insights-ocp-scanner:latest
#       type: ImageChange
kind: List
metadata: {}
